from __future__ import annotations

import copy
import json
import pennylane as qml
import torch

from abc import ABC, abstractmethod

ENCODING_OPTIONS = ["basis", "rx_angle", "ry_angle", "rz_angle", "amplitude", "linear_u3"]


def initialize_encoder(target: str, encoding_str: str, n_features: int, n_qubits: int) -> Encoder:
    """
    Given the target system (e.g., pennylane or qiskit) create a
    new encoder to perform encodings from classical to quantum 
    which will set the input parameter and input gate for each wire.

    Args:
        target: the target system (pennylane or qiskit)
        encoding_str: a string representation of the encoder
            to be created
        n_features: how many classical input features will be used.
        n_qubits: how many qubits will be used as inputs for the
            quantum circuit.
    """

    encoder = None

    if target == "pennylane":
        if encoding_str == "basis":
            encoder = PennylaneBasisEncoder(n_features, n_qubits)

        elif encoding_str == "rx_angle":
            encoder = PennylaneRXAngleEncoder(n_features, n_qubits)

        elif encoding_str == "ry_angle":
            encoder = PennylaneRYAngleEncoder(n_features, n_qubits)

        elif encoding_str == "rz_angle":
            encoder = PennylaneRZAngleEncoder(n_features, n_qubits)

        elif encoding_str == "amplitude":
            encoder = PennylaneAmplitudeEncoder(n_features, n_qubits)

        elif encoding_str == "linear_u3":
            encoder = PennylaneLinearU3Encoder(n_features, n_qubits)

        else:
            raise ValueError(f"Unknown encoder={encoding_str} for target={target}")
    else:
            raise ValueError(f"Unknown encoder={encoding_str} for target={target}")

    return encoder


class Encoder(ABC):
    def __init__(self, n_features: int, n_qubits: int):
        """
        Base constructor for a decoder, as each will need to know how many
        qubits it needs to decode to.

        Args:
            n_features: how many classical input features will be used.
            n_qubits: how many qubits will be used as inputs for the
                quantum circuit.
        """
        self.n_features = n_features
        self.n_qubits = n_qubits

    @abstractmethod
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Given the torch tensor of input values and the circuit genome,
        this should set the input qubits of the quantum circuit model
        being used for pytorch forward/backward passes.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        pass

    def to_dict(self) -> dict[str, any]:
        """
        This converts the encoder to a dict so it can be written as
        JSON for passing via MPI message passing, or saved to disk.

        The default is just to write the class name and then arguments
        used to construct the encoder in the args entry. This allows
        us to use a standard method with reflection for construcing
        the encoders backfrom JSON.
        """

        response_dict = {
            "class": type(self).__name__,
            "args": {
                "n_features": self.n_features,
                "n_qubits": self.n_qubits,
            }
        }

        # for Decoders that are pytorch modules, also save
        # their parameters (so we don't need to reimplement 
        # this for each of them).
        if isinstance(self, torch.nn.Module):
            state_dict = self.state_dict()

            serialized_dict = {
                name: tensor.cpu().numpy().tolist() for name, tensor in state_dict.items()
            }

            '''
            logger.debug("serialized nn.Module tensor dict:")
            logger.debug(json.dumps(serialized_dict, indent=4))
            '''

            response_dict["args"]["state_dict"] = serialized_dict

        # logger.debug("encoder json is:")
        # logger.debug(json.dumps(response_dict, ensure_ascii=False, indent=4))

        return response_dict

    @classmethod
    def from_dict(cls, serialized: dict[str, any]) -> Encoder:
        """
        Given a dict created from the serialized JSON generated by the
        `to_dict` method, create the class with the given args from
        the JSON.

        Args:
            serialized: is the dict created from the serialized JSON.

        Returns:
            A constructed Decoder object created from the given JSON.
        """

        # remove the module parameters so we can call the default
        #constructor
        serialized_state_dict = None
        if "state_dict" in serialized["args"].keys():
            serialized_state_dict = serialized["args"].pop("state_dict")

        class_init = globals()[serialized["class"]]
        class_object = class_init(**serialized["args"])

        if isinstance(class_object, torch.nn.Module):
            # convert the JSON values back into tensors
            state_dict = {
                name: torch.tensor(list_data)
                for name, list_data in serialized_state_dict.items()
            }

            # set the module's parameter tensors
            class_object.load_state_dict(state_dict)

        return class_object

    def copy(self) -> Encoder:
        """
        Creates a copy of the encoder (if needed) so modifying a genome's
        encoder does not effect the one of its parent.
        """
        pass



class PennylaneBasisEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies a basis embedding from the input values to the input
        wires of the quantum circuit.

        Args:
            inputs: the x (input) tensor for a sample. These need to be
                binary values, and the number of qubits in the circuit
                need to be equal to the number of binary values.
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        qml.BasisState(inputs, wires=genome.input_indexes)

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self

class PennylaneRXAngleEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies an angle incoding from the input values to the input
        wires of the quantum circuit with RX gates.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        for i, w in enumerate(genome.input_indexes):
            qml.RX(torch.pi * inputs[i], wires=w)

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self



class PennylaneRYAngleEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies an angle incoding from the input values to the input
        wires of the quantum circuit with RY gates.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        for i, w in enumerate(genome.input_indexes):
            qml.RY(torch.pi * inputs[i], wires=w)

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self



class PennylaneRZAngleEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies an angle incoding from the input values to the input
        wires of the quantum circuit with RZ gates.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        for i, w in enumerate(genome.input_indexes):
            qml.RZ(torch.pi * inputs[i], wires=w)

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self



class PennylaneAmplitudeEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies an amplitude embedding from the input values to the input
        wires of the quantum circuit.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """

        # expects float tensor of length 2**len(in_wires)
        qml.AmplitudeEmbedding(
            features=inputs,
            wires=genome.input_indexes,
            normalize=True,
            pad_with=0.0,
        )

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self


class PennylaneLinearU3Encoder(Encoder, torch.nn.Module):
    def __init__(self, n_features: int, n_qubits: int):
        """
        Base constructor for a decoder, as each will need to know how many
        outputs it needs to decode to.

        Args:
            n_features: how many classical input features will be used.
            n_qubits: how many qubits will be used as inputs for the
                quantum circuit.
        """
        # initialize both superclasses
        torch.nn.Module.__init__(self)
        Encoder.__init__(self, n_features, n_qubits)

        print(f"creating linear U3 encoder with n_features: {n_features} and n_qubits: {n_qubits}")

        # each qubit will get 3 parameters from the outputs of the linear layer
        self.layer = torch.nn.Linear(self.n_features, self.n_qubits * 3)

        # initalize the layer weights randomly
        torch.nn.init.xavier_uniform_(self.layer.weight)
        torch.nn.init.zeros_(self.layer.bias)

    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies a linear embedding from the input values to the input
        wires of the quantum circuit as U3 gates.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """

        '''
        print(f"forward on linear incoder, inputs: {inputs}, type: {inputs.dtype}")
        print(f"weights: {self.layer.weight}, type: {self.layer.weight.dtype}")
        print(f"biases: {self.layer.bias}, type: {self.layer.bias.dtype}")
        '''

        # linear layer requires float32 values
        encoding = self.layer(inputs.float())

        for i, w in enumerate(genome.input_indexes):
            # every qubit gets 3 of the encoding values as U3 parameters 
            start = i * 3
            qml.U3(encoding[i], encoding[i+1], encoding[i+2], wires=w)


    def copy(self) -> Encoder:
        """
        Returns:
            A deepcopy of this decoder so if it can be reused by child
            genomes without modifying the parents decoder.
        """
        return copy.deepcopy(self)


