from __future__ import annotations

import copy
import json
import pennylane as qml
import torch

from abc import ABC, abstractmethod

ENCODING_OPTIONS = ["identity", "linear"]


def initialize_encoder(target: str, encoding_str: str, n_inputs: int, n_outputs: int) -> Encoder:
    """
    Given the target system (e.g., pennylane or qiskit) create a
    new encoder to perform encodings from classical to quantum 
    which will set the input parameter and input gate for each wire.

    Args:
        target: the target system (pennylane or qiskit)
        encoding_str: a string representation of the encoder
            to be created
        n_inputs: how many classical input features will be used.
        n_outputs: how many values in the output of the encoder, which
            will be used as inputs for the quantum circuit.
    """

    encoder = None

    if encoding_str == "linear":
        encoder = LinearEncoder(n_inputs, n_outputs)

    elif encoding_str == "identity":
        encoder = IdentityEncoder(n_inputs, n_outputs)

    else:
        raise ValueError(f"Unknown encoder={encoding_str} for target={target}")

    return encoder


class Encoder(ABC):
    def __init__(self, n_inputs: int, n_outputs: int):
        """
        Base constructor for a decoder, as each will need to know how many
        qubits it needs to decode to.

        Args:
            n_inputs: how many classical input features will be used.
            n_outputs: how many values in the output of the encoder, which
                will be used as inputs for the quantum circuit.
        """
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs

    @abstractmethod
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Given the torch tensor of input values and the circuit genome,
        this should set the input qubits of the quantum circuit model
        being used for pytorch forward/backward passes.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        pass

    def to_dict(self) -> dict[str, any]:
        """
        This converts the encoder to a dict so it can be written as
        JSON for passing via MPI message passing, or saved to disk.

        The default is just to write the class name and then arguments
        used to construct the encoder in the args entry. This allows
        us to use a standard method with reflection for construcing
        the encoders backfrom JSON.
        """

        response_dict = {
            "class": type(self).__name__,
            "args": {
                "n_inputs": self.n_inputs,
                "n_outputs": self.n_outputs,
            }
        }

        # for Decoders that are pytorch modules, also save
        # their parameters (so we don't need to reimplement 
        # this for each of them).
        if isinstance(self, torch.nn.Module):
            state_dict = self.state_dict()

            serialized_dict = {
                name: tensor.cpu().numpy().tolist() for name, tensor in state_dict.items()
            }

            '''
            logger.debug("serialized nn.Module tensor dict:")
            logger.debug(json.dumps(serialized_dict, indent=4))
            '''

            response_dict["args"]["state_dict"] = serialized_dict

        # logger.debug("encoder json is:")
        # logger.debug(json.dumps(response_dict, ensure_ascii=False, indent=4))

        return response_dict

    @classmethod
    def from_dict(cls, serialized: dict[str, any]) -> Encoder:
        """
        Given a dict created from the serialized JSON generated by the
        `to_dict` method, create the class with the given args from
        the JSON.

        Args:
            serialized: is the dict created from the serialized JSON.

        Returns:
            A constructed Decoder object created from the given JSON.
        """

        # remove the module parameters so we can call the default
        #constructor
        serialized_state_dict = None
        if "state_dict" in serialized["args"].keys():
            serialized_state_dict = serialized["args"].pop("state_dict")

        class_init = globals()[serialized["class"]]
        class_object = class_init(**serialized["args"])

        if isinstance(class_object, torch.nn.Module):
            # convert the JSON values back into tensors
            state_dict = {
                name: torch.tensor(list_data)
                for name, list_data in serialized_state_dict.items()
            }

            # set the module's parameter tensors
            class_object.load_state_dict(state_dict)

        return class_object

    def copy(self) -> Encoder:
        """
        Creates a copy of the encoder (if needed) so modifying a genome's
        encoder does not effect the one of its parent.
        """
        pass



class IdentityEncoder(Encoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        A default encoder for basis and angle encodings, which simply returns
        the same inputs.

        Args:
            inputs: the x (input) tensor for a sample, this will be the
                same as the output. 
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """

        return inputs

    def copy(self) -> Encoder:
        """
        This encoder has no state so we don't need to do a copy.
        """
        return self


class LinearEncoder(Encoder, torch.nn.Module):
    def __init__(self, n_inputs: int, n_outputs: int):
        """
        Base constructor for a decoder, as each will need to know how many
        outputs it needs to decode to.

        Args:
            n_inputs: how many classical input features will be used.
            n_outputs: how many outputs from the linear encoder, which should
                be the same as the number of qubits that will be used as inputs 
                for the quantum circuit.
        """
        # initialize both superclasses
        torch.nn.Module.__init__(self)
        Encoder.__init__(self, n_inputs, n_outputs)

        print(f"creating linear encoder with n_inputs: {n_inputs} and n_outputs: {n_outputs}")

        self.layer = torch.nn.Linear(self.n_inputs, self.n_outputs)

        # initalize the layer weights randomly
        torch.nn.init.xavier_uniform_(self.layer.weight)
        torch.nn.init.zeros_(self.layer.bias)

    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Applies a linear embedding from the input values to the input
        wires of the quantum circuit as U3 gates.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """

        '''
        print(f"forward on linear incoder, inputs: {inputs}, type: {inputs.dtype}")
        print(f"weights: {self.layer.weight}, type: {self.layer.weight.dtype}")
        print(f"biases: {self.layer.bias}, type: {self.layer.bias.dtype}")
        '''

        # linear layer requires float32 values
        encoding = self.layer(inputs.float())

        return encoding

    def copy(self) -> Encoder:
        """
        Returns:
            A deepcopy of this decoder so if it can be reused by child
            genomes without modifying the parents decoder.
        """
        return copy.deepcopy(self)


